version: '3.7'
services:
  db:
    image: mongo:latest
     
  nodeauth:
    build: .
    restart: always
    ports:
      - "3551:3551"
    environment:
      PORT: 3551
      MONGOURL: mongodb://127.0.0.1:27017/user  
    depends_on:
     - db  
